services:
  masternode:
    build: .
    container_name: masternode
    networks:
      - hadoop_network
    command: ["tail", "-f", "/dev/null"]
    storage_opt:
      size: 500MB

  slavenode1:
    build: .
    container_name: slavenode1
    networks:
      - hadoop_network
    command: ["tail", "-f", "/dev/null"]
    storage_opt:
      size: 500MB

  slavenode2:
    build: .
    container_name: slavenode2
    networks:
      - hadoop_network
    command: ["tail", "-f", "/dev/null"]
    storage_opt:
      size: 500MB

networks:
  hadoop_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

